version: '3.8'

services:
  tiendaonline-mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  tiendaonline-meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_HTTP_ADDR=0.0.0.0:7700
      - MEILI_MASTER_KEY=masterKey
    ports:
      - "7700:7700"
    volumes:
      - meili-data:/data.ms

  tiendaonline-server:
    build:
      context: .
      dockerfile: TiendaOnline.Server/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=tiendaonline-mssql,1433;Database=tiendaonline;User Id=sa;Password=YourStrong!Passw0rd;
      - Meilisearch__ServerUrl=http://tiendaonline-meilisearch:7700
      - Meilisearch__MasterKey=masterKey
      - Jwt__SecretKey=devsecret
      - CorsSettings__AllowedOrigins=http://localhost:5173
    ports:
      - "8080:80"
    depends_on:
      - tiendaonline-mssql
      - tiendaonline-meilisearch

volumes:
  mssql-data:
  meili-data:
# Dockerfile simple que usa la imagen oficial de Meilisearch
FROM getmeili/meilisearch:latest

# Meilisearch escuchará en 0.0.0.0:7700 dentro del contenedor
ENV MEILI_HTTP_ADDR=0.0.0.0:7700
# La clave master se definirá desde las env vars de Render (MEILI_MASTER_KEY)
# Puedes definir un valor por defecto aquí si lo deseas.

EXPOSE 7700

# La imagen oficial ya define el entrypoint correcto, pero lo ponemos explícito
ENTRYPOINT ["meilisearch"]

