# render.yaml para desplegar servicios en Render usando Docker
# Servicios configurados aquí:
#  - tiendaonline-server : backend (.NET 9) público
#  - tiendaonline-meilisearch : Meilisearch (internal)
# Nota: El despliegue de SQL Server en contenedor en Render suele fallar por permisos/limitaciones de la plataforma.
# Recomendación: usar una base de datos gestionada (Azure SQL, RDS, Render Database) en producción.

services:
  - type: web
    name: tiendaonline-server
    env: docker
    dockerfilePath: TiendaOnline.Server/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_RUNNING_IN_CONTAINER
        value: "true"
      # Configura estas variables en la UI de Render (no en el repo):
      # ConnectionStrings__DefaultConnection (ej. Azure SQL o Render DB)
      # Meilisearch__ServerUrl (ej. http://tiendaonline-meilisearch:7700 si usas Meilisearch interno)
      # Meilisearch__MasterKey
      # Jwt__SecretKey
      # CorsSettings__AllowedOrigins

  - type: web
    name: tiendaonline-meilisearch
    env: docker
    dockerfilePath: deploy/meilisearch/Dockerfile
    plan: free
    internal: true
    envVars:
      - key: MEILI_MASTER_KEY
        value: masterKey
      - key: MEILI_HTTP_ADDR
        value: 0.0.0.0:7700

# Discos y detalles de la DB:
# - Si necesitas Meilisearch persistente, crea un Persistent Disk y móntalo en /data.ms para el servicio tiendaonline-meilisearch.
# - Para la base de datos, en lugar de crear un servicio MSSQL en Render (no recomendado), crea un servicio de base de datos gestionada
#   y configura en el servicio `tiendaonline-server` la env var `ConnectionStrings__DefaultConnection` con la cadena adecuada.
# Ejemplos de ConnectionString:
#  - Azure SQL:
#    Server=tcp:<your-server>.database.windows.net,1433;Initial Catalog=TiendaOnline;Persist Security Info=False;User ID=<user>;Password=<password>;Encrypt=True;Connection Timeout=30;
#  - Render Postgres (si migras a Postgres):
#    Host=<host>;Port=5432;Database=tiendaonline;Username=<user>;Password=<password>

# Notas finales:
# - No guardes secretos en el repo. Define SA/DB/JWT/Meili keys en Settings -> Environment of the specific service in Render.
# - Si quieres que gestione la migración a Postgres o que quite el servicio MSSQL del repo render.yaml para que no intente desplegarlo, dímelo y lo actualizo.
